all:
	$(MAKE) -C ./libtaucore
	$(MAKE) -C ./libtaumath
	$(MAKE) -C ./libtaugraphics
	$(MAKE) -C ./libtauopengl

clean:
	$(MAKE) -C ./libtaucore clean
	$(MAKE) -C ./libtaumath clean
	$(MAKE) -C ./libtaugraphics clean
	$(MAKE) -C ./libtauopengl clean
	
rebuild:
	$(MAKE) -C ./libtaucore rebuild
	$(MAKE) -C ./libtaumath rebuild
	$(MAKE) -C ./libtaugraphics rebuild
	$(MAKE) -C ./libtauopengl rebuild
